//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiviaMaui.Resources.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiviaMaui.Resources.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your access token.
        /// </summary>
        internal static string configurationAccessTokenPlaceholder {
            get {
                return ResourceManager.GetString("configurationAccessTokenPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token.
        /// </summary>
        internal static string configurationAccessTokenTitle {
            get {
                return ResourceManager.GetString("configurationAccessTokenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Notifications.
        /// </summary>
        internal static string configurationEnableNotifications {
            get {
                return ResourceManager.GetString("configurationEnableNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Password.
        /// </summary>
        internal static string configurationHidePassword {
            get {
                return ResourceManager.GetString("configurationHidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Password.
        /// </summary>
        internal static string configurationShowPassword {
            get {
                return ResourceManager.GetString("configurationShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token cannot be empty!.
        /// </summary>
        internal static string configurationTokenEmpty {
            get {
                return ResourceManager.GetString("configurationTokenEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token saved successfully!.
        /// </summary>
        internal static string configurationTokenSavedSuccess {
            get {
                return ResourceManager.GetString("configurationTokenSavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Directory to Monitor.
        /// </summary>
        internal static string directoryMonitorNewDirectory {
            get {
                return ResourceManager.GetString("directoryMonitorNewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No directories being monitored.
        /// </summary>
        internal static string directoryNoDirectoriesMonitored {
            get {
                return ResourceManager.GetString("directoryNoDirectoriesMonitored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected directory?.
        /// </summary>
        internal static string editdirectoryConfirmDeleteMessage {
            get {
                return ResourceManager.GetString("editdirectoryConfirmDeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Directory.
        /// </summary>
        internal static string editdirectoryDeleteDirectory {
            get {
                return ResourceManager.GetString("editdirectoryDeleteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Configuration Page.
        /// </summary>
        internal static string goToConfig {
            get {
                return ResourceManager.GetString("goToConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Directories Page.
        /// </summary>
        internal static string goToDirectories {
            get {
                return ResourceManager.GetString("goToDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to History Page.
        /// </summary>
        internal static string goToHistory {
            get {
                return ResourceManager.GetString("goToHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Images.
        /// </summary>
        internal static string goToImages {
            get {
                return ResourceManager.GetString("goToImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Models.
        /// </summary>
        internal static string goToModels {
            get {
                return ResourceManager.GetString("goToModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear History.
        /// </summary>
        internal static string historyClearHistory {
            get {
                return ResourceManager.GetString("historyClearHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clear all history entries? This action cannot be undone..
        /// </summary>
        internal static string historyClearHistoryConfirmMessage {
            get {
                return ResourceManager.GetString("historyClearHistoryConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this image?.
        /// </summary>
        internal static string imagesDeleteConfirmMessage {
            get {
                return ResourceManager.GetString("imagesDeleteConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The image has been deleted..
        /// </summary>
        internal static string imagesImageDeleted {
            get {
                return ResourceManager.GetString("imagesImageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Filepath.
        /// </summary>
        internal static string newdirectoryFolderLabel {
            get {
                return ResourceManager.GetString("newdirectoryFolderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter directory filepath.
        /// </summary>
        internal static string newdirectoryFolderPlaceholder {
            get {
                return ResourceManager.GetString("newdirectoryFolderPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide both the directory name and its filepath..
        /// </summary>
        internal static string newdirectoryMissingInfo {
            get {
                return ResourceManager.GetString("newdirectoryMissingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string newdirectoryModels {
            get {
                return ResourceManager.GetString("newdirectoryModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the Directory.
        /// </summary>
        internal static string newdirectoryNameLabel {
            get {
                return ResourceManager.GetString("newdirectoryNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter name of directory.
        /// </summary>
        internal static string newdirectoryNamePlaceholder {
            get {
                return ResourceManager.GetString("newdirectoryNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick Folder.
        /// </summary>
        internal static string newdirectoryPickFolder {
            get {
                return ResourceManager.GetString("newdirectoryPickFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Monitored Directory.
        /// </summary>
        internal static string newdirectorySaveDirectory {
            get {
                return ResourceManager.GetString("newdirectorySaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory saved successfully!.
        /// </summary>
        internal static string newdirectorySavedSuccess {
            get {
                return ResourceManager.GetString("newdirectorySavedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load models. Please check your internet connection or configuration..
        /// </summary>
        internal static string newdirectoryUnableToLoadModels {
            get {
                return ResourceManager.GetString("newdirectoryUnableToLoadModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to pick the folder. Ensure the folder is accessible and permissions are set correctly..
        /// </summary>
        internal static string newdirectoryUnableToPickFolder {
            get {
                return ResourceManager.GetString("newdirectoryUnableToPickFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
