# This workflow will build a .NET MAUI Android project
name: Build MiViA Client Android
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install MAUI workload
        run: dotnet workload install maui

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "microsoft"
          java-version: "17"

      - name: Build Android App
        run: dotnet publish MiviaMaui.csproj -c Release -f:net8.0-android

      - name: Run Tests in MiviaTest
        run: |
          cd MiviaTest
          dotnet test
          cd ..

      - name: Upload APK
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: android-package
          path: bin/Release/net8.0-android/*Signed.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          files: bin/Release/net8.0-android/*Signed.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
